apiVersion: v1
kind: Service
metadata:
  name: user-mcs
spec:
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    # nodePort: 32100
  selector:
    app: user-deployment
  type: NodePort